### ISSUE TITLE
Release of code and datasets

### ISSUE THREAD

**Issue by LinLin1031** [PRBonn/plant_pcd_segmenter#1]
Thank you very much for your wonderful work. I would like to know when the code and dataset will be released. @niosus @stachnis @nivedchebrolu @ovysotska @lassepe

**Comment by markselias** [comment]
The code is available in the repo and the dataset is now available as well at [this link](https://bonnbeetclouds3d.ipb.uni-bonn.de/). Hope you find it useful!
